apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: clawops
data:
  N8N_HOST: "INJECT_N8N_HOST"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  WEBHOOK_URL: "http://INJECT_N8N_HOST/"
  N8N_USER_MANAGEMENT_DISABLED: "false"
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "INJECT_N8N_PASSWORD"
  N8N_USER_FOLDER: "/home/node/.n8n"
  MCP_URL: "http://mcp-server.clawops.svc.cluster.local:8000"
  PROMETHEUS_URL: "INJECT_PROMETHEUS_URL"
  N8N_SECURE_COOKIE: "false"
  DASHBOARD_URL: "http://clawops-dashboard.clawops.svc.cluster.local:80"
