apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app
  labels:
    app: payments
    scenario: crashloop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: busybox
          command: ["sh", "-c", "echo Starting payments && sleep 5 && exit 1"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
